name: Zig CI

# Triggers the workflow on push events to the 'stable' branch
on:
  push:
    branches: [stable]

jobs:
  test:
    # Use a Linux runner for the CI job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        # A community-maintained action to easily install a Zig compiler
        uses: mlugg/setup-zig@v2
        with:
          # Replace this with the Zig version you want to use, e.g., 0.12.0
          version: 0.15.2

      - name: Build and Run Tests
        # This command is common for Zig projects using 'zig build'
        run: zig build test
        # If 'zig build test' fails (exits with non-zero), the step fails,
        # and consequently, the entire job and workflow will fail.
